import pandas as pd
import geopandas
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

#load the state incident counts generated by C++
df = pd.read_csv('build/Release/state_incident_counts.csv')

# load a shapefile of US states (ex, from Natural Earth
# https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/)
world = geopandas.read_file(r'C:/Users/pquin/Downloads/ne_10m_admin_1_states_provinces/ne_10m_admin_1_states_provinces.shp')
states = world[world['name'].isin(df['State'].unique())] # Filter to only states in our data

# Merge incident data with state geometries
merged = states.set_index('name').join(df.set_index('State'))

# Create a colormap for the incidents 
cmap = plt.cm.viridis
normalize = mcolors.Normalize(vmin=merged['IncidentCount'].min(), vmax=merged['IncidentCount'].max())

# Plot the states with incident counts
fig, ax = plt.subplots(1, 1, figsize=(15, 10))
merged.plot(column='IncidentCount', cmap=cmap, linewidth=0.8, ax=ax, edgecolor='0.8', legend=True, norm=normalize, legend_kwds={'label': "Total amount of documented immigration into US (per state)",'orientation': "horizontal"})
ax.set_title('Total Counts of Legal Entry by State, Data by Department of Defense', fontdict={'fontsize': '15', 'fontweight' : '3'})
ax.axis('off')

plt.show()

print ("\n-- Media Bias Thesis Discussion ---")
print ("This visualization illustrates the conflict of real life data and bias in media reporting.\n")
print ("Does the media focus on states with the highest actual volume/traffic, or elsewhere? \n")
print ("This visualization is the qualitative showcase for my thesis.")

